- hosts: all
  become: yes
  roles:
    - common-init
    - install-local-facts

- hosts: local_boxes
  become: yes
  roles:
    - add-host-references
    - configure-yum-repo
    - local-yum-repo
    - openssl-cert

- hosts:
    - dev_archaeology
  become: yes
  roles:
