- hosts: all
  become: yes
  roles:
    - common-init
    - install-local-facts

- hosts: ddbim
  become: yes
  roles:
#    - add-host-references
    - configure-yum-repo
    - local-yum-repo
    - install-local-facts
    - openssl-cert
    - install-httpd
    - deploy-druid
    - deploy-superset

#- hosts:
#    - dev_bi_metrics
#  become: yes
#  roles:
#    - install-local-facts
#    - configure-yum-repo